[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Unrecognised tag: 'databasepassword' (position: START_TAG seen ...</localRepository>\n  -->\n  \n  <databasepassword>... @56:21)  @ C:\Program Files\Apache Software Foundation\apache-maven-3.5.3\bin\..\conf\settings.xml, line 56, column 21
[WARNING] 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO] 
[INFO] ----------------------< com.softserve.edu:lv344 >-----------------------
[INFO] Building lv344 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ lv344 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ lv344 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ lv344 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ lv344 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- webdriverextensions-maven-plugin:3.1.3:install-drivers (pre-test) @ lv344 ---
[INFO] Installation directory "C:\Users\yharasym\workspace\lv344\target\test-classes"
[INFO] Installing drivers from configuration
[INFO] chromedriver-windows-32bit version 2.42.0
[INFO]   Already installed
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ lv344 ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
	***testApp5() Error Check ...
itr.getName() = testApp5
itr.getMethod().getMethodName() = testApp5

**********
FAILED: testApp5
**java.lang.AssertionError: expected [4] but found [3]
**        at org.testng.Assert.fail(Assert.java:96)
**        at org.testng.Assert.failNotEquals(Assert.java:776)
**        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
**        at org.testng.Assert.assertEquals(Assert.java:118)
**        at org.testng.Assert.assertEquals(Assert.java:652)
**        at org.testng.Assert.assertEquals(Assert.java:662)
**        at com.softserve.edu.AppTestReport.testApp5(AppTestReport.java:131)
**        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
**        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
**        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
**        at java.lang.reflect.Method.invoke(Method.java:498)
**        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
**        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
**        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
**        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
**        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
**        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
**        at org.testng.TestRunner.privateRun(TestRunner.java:648)
**        at org.testng.TestRunner.run(TestRunner.java:505)
**        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
**        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
**        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
**        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
**        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
**        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
**        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
**        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
**        at org.testng.TestNG.runSuites(TestNG.java:1049)
**        at org.testng.TestNG.run(TestNG.java:1017)
**        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
**        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
**        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
**        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
**        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
**        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
**        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
[ERROR] 1:22:05 PM EEST ср @AfterMethod for:

**********
FAILED: testApp5
**java.lang.AssertionError: expected [4] but found [3]
**        at org.testng.Assert.fail(Assert.java:96)
**        at org.testng.Assert.failNotEquals(Assert.java:776)
**        at org.testng.Assert.assertEqualsImpl(Assert.java:137)
**        at org.testng.Assert.assertEquals(Assert.java:118)
**        at org.testng.Assert.assertEquals(Assert.java:652)
**        at org.testng.Assert.assertEquals(Assert.java:662)
**        at com.softserve.edu.AppTestReport.testApp5(AppTestReport.java:131)
**        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
**        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
**        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
**        at java.lang.reflect.Method.invoke(Method.java:498)
**        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
**        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
**        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
**        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
**        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
**        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
**        at org.testng.TestRunner.privateRun(TestRunner.java:648)
**        at org.testng.TestRunner.run(TestRunner.java:505)
**        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
**        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
**        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
**        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
**        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
**        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
**        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
**        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
**        at org.testng.TestNG.runSuites(TestNG.java:1049)
**        at org.testng.TestNG.run(TestNG.java:1017)
**        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
**        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
**        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
**        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
**        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
**        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
**        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
===== Invoked methods
    AppTestReport.testApp5()[pri:0, instance:com.softserve.edu.AppTestReport@43a0cee9] 1134612201
  AppTestReport.tearDown2(org.testng.ITestResult)[pri:0, instance:com.softserve.edu.AppTestReport@43a0cee9][TestResult name=testApp5 status=FAILURE method=AppTestReport.testApp5()[pri:0, instance:com.softserve.edu.AppTestReport@43a0cee9] output={null}]  1134612201
=====
FAILED: testApp5
java.lang.AssertionError: expected [4] but found [3]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at com.softserve.edu.AppTestReport.testApp5(AppTestReport.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)


===============================================
    Test1
    Tests run: 1, Failures: 1, Skips: 0
===============================================

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.69 s <<< FAILURE! - in TestSuite
[ERROR] testApp5(com.softserve.edu.AppTestReport)  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: expected [4] but found [3]
	at com.softserve.edu.AppTestReport.testApp5(AppTestReport.java:131)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AppTestReport.testApp5:131 expected [4] but found [3]
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.630 s
[INFO] Finished at: 2018-10-24T13:22:06+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project lv344: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\yharasym\workspace\lv344\target\surefire-reports\test-output for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
